### ISSUE TITLE
Permafrost needs to take into account creative maps as well

### ISSUE THREAD

**Issue by Tsoccerguy3** [Virtuoel/Permafrost#2]
You have 1 scenario hard coded into the mod .With the mod installed with mine iI'm getting some melting . In a creative map , example 
; ice is still used as a decorative block , example windows , etc ..
Snow layers have been used to make furniture , building veneers , etc ...  

To have more control over the snow and ice can you add a few settings ie.
- to stop all ice from melting example Block_Ice drops Block_Ice , is one way
or Update ticks on snow and ice controllable from 0 -3
more controls would be a good thing
Thanks

Looks good a "Game of Thrones "  white walkers  , winters coming inspired mod

**Comment by Virtuoel** [comment]
I'm not entirely sure what you mean about the settings part. Could you reword that a bit?
Are you asking for config options to control each part of the mod, e.g. a config value for if snow should melt or not, another for ice, options for the forming part, etc?

Also "With the mod installed with mine", which mod of yours are you referring to?

**Comment by Tsoccerguy3** [comment]
Yes . Turning ice and snow melt on or off in some sort of settings .   I have a core mod that I use for working on various server maps while offline https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1286894-1-12-1-11-2-1-10-2-1-9-4-1-8-9-1-7-10-etc-updated
I've been using the coremod to stop ice melting and prevent accidentally damaging a map

With the newer Minecraft versions , I could use the gamerule randomTickSpeed = 0 to freeze the whole map from updating . This also stops the ice and snow melting , but over kill because it stops all updates.  Yours is a better idea , to implement  settings .

**Comment by Virtuoel** [comment]
Resolved as of cd1f265. Everything now has toggles in the config.
